server:
  port: 8056
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://121.89.170.193:3306/oa?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
      # 开发/测试/生产环境分别对应dev/test/prod
      # 注意：只有在开发模式下才能开启 跨域访问，
    active: dev


